CREATE TABLE membres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT,
    instruments TEXT,
    status TEXT DEFAULT 'active'
);

CREATE TABLE evenements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT,
    heure TEXT,
    titre TEXT,
    type TEXT,
    lieu TEXT
);

CREATE TABLE presences (
    membre_id INTEGER,
    evenement_id INTEGER,
    statut TEXT,
    PRIMARY KEY (membre_id, evenement_id),

    CONSTRAINT fk_membre
        FOREIGN KEY (membre_id)
        REFERENCES membres(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_evenement
        FOREIGN KEY (evenement_id)
        REFERENCES evenements(id)
        ON DELETE CASCADE
);

CREATE TABLE morceaux (
    id SERIAL PRIMARY KEY,
    titre TEXT NOT NULL UNIQUE
);

CREATE TABLE partitions (
    id SERIAL PRIMARY KEY,
    morceau_id INTEGER NOT NULL REFERENCES morceaux(id) ON DELETE CASCADE,
    instrument TEXT NOT NULL,
    fichier TEXT NOT NULL,
    date_ajout TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (morceau_id, instrument)
);
